set(_CATKIN_CURRENT_PACKAGE "ir_control")
set(ir_control_MAINTAINER "pi <pi@todo.todo>")
set(ir_control_DEPRECATED "")
set(ir_control_VERSION "0.0.0")
set(ir_control_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(ir_control_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(ir_control_BUILDTOOL_DEPENDS "catkin")